[package]
name = "server"
version = "0.1.0"
authors = ["bleepster <earl.lapus@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
dns-lookup = "0.9.0"
nix = "0.18.0"
